enarx/ciborium

- src/ser/mod.rs
The deserializer was already set. The inconsistency between the two
caused uuid::Uuid to perform human readable serialization, which it then
couldn't decode.
Resolves: #3
Signed-off-by: Nathaniel McCallum <npmccallum@redhat.com>
> Mark the serializer as not human readable

- README.md
- src/de/mod.rs
- src/lib.rs
- src/ser/mod.rs
Rust doc in 1.48 added links to types, so to make it easier to get to
the mentioned types, add links in the doc strings.
> doc: add links to types referenced

- ciborium/src/value/float.rs
- ciborium/src/value/integer.rs
- ciborium/src/value/mod.rs
Hello,
this PR introduces some utility functions to easily extract data out of generic `Value` objects. This is inspired by the utilities you get with `serde_json` for their respective `Value` type (see https://github.com/serde-rs/json/blob/master/src/value/mod.rs#L345).
Here's an example of how this might work:
```rust
use ciborium::value::Value;
let mut value = Value::Array(
vec![
Value::Text(String::from("foo")),
Value::Text(String::from("bar"))
]
);
value.as_array_mut().unwrap().clear();
assert_eq!(value, Value::Array(vec![]));
```
> `ciborium::value::Value` data extraction utils (inspired by `serde_json`)

- ciborium/src/value/canonical.rs
- ciborium/src/value/integer.rs
- ciborium/src/value/mod.rs
- ciborium/tests/canonical.rs
This allows programs to sort maps according to the canonical sorting rules.
The Value itself is good with the other canonical rules.
Fixes #28
> Add a new CanonicalValue type

- ciborium/src/value/mod.rs
I propose the implementation of `into_` helpers for `Value`. I opted for some design choices, which can reconsider without problem:
- Return values are `Result`s, and the `Err` type is `Self`. In this way the `value` is not lost if the conversion fails. Maybe it is a bit less ergonomic than returning `Option`, but it should be slightly more powerful.
- I used `Self` in `Err`, but `Value` in `Ok` for nested things like `Array` and `Map`. This is only to avoid types like `Return<Vec<Self>, Self>`, which can be slightly confusing.
- I decided to implement `into_` methods for `Copy` types as well. I made it for consistency, but to be honest I am a bit unsure.
- I omitted `into_null`, which would have the following signature:
```rust
fn into_null(self) -> Result<(), Self>
```
I think that this …
> Add into_* methods to Value

- LICENSE
- ciborium-io/LICENSE
- ciborium-ll/LICENSE
Add symlinks to include the license text in the ciborium-ll and ciborium-io crates. Also add one in the repo toplevel while at it, mostly for github to pick up.
> Include license text in all published crates

- ciborium/src/de/mod.rs
- ciborium/tests/codec.rs
This change makes it possible to decode a `serde_bytes::ByteBuf` from
CBOR data encoded as a `Vec<u8>` (and in the other direction, too).
The `ByteBuf` -> `Vec<u8>` direction is not optimal because it allocates
an additional buffer, but this should not be a problem because decoding
one byte at a time ruins performance anyway.
Context: our project migrates from serde_cbor to ciborium.
ciborium is faster and generates compact code, but we have old data sets
generated using inefficient `Vec<u8>` encoding. We want to be able to
decode them with ciborium, which currently does not provide
compatibility between `Vec<u8>` and `ByteBuf` as serde_cbor did.
Signed-off-by: Roman Kashitsyn <roman@dfinity.org>
> feat: transparent conversion between ByteBuf and Vec<u8>

- ciborium-io/Cargo.toml
- ciborium-ll/Cargo.toml
- ciborium/Cargo.toml
I spent a little while chasing my tail trying to figure out how best to use `ciborium-io` with a `std::io::Write` value, when the impl was there all along 🤦🏻‍♂️
This bit of package metadata should make `docs.rs` build with the `"std"` feature enabled, so the impl will show up in the generated documentation.
> Build with `std` on docs.rs

- ciborium-ll/src/enc.rs
Fix two cases where `.unwrap_or_else()` can be replaced with `.unwrap_or()` without causing other problems. Clippy flagged both of these, and they seem like reasonable suggestions.
> fix: two instances of `clippy::unnecessary_lazy_evaluations`

- ciborium-ll/src/seg.rs
- ciborium/src/de/mod.rs
- ciborium/tests/codec.rs
I'm not able to deserialize CBOR maps where keys has been encoded as byte strings (type 2). This change handles both types of strings from CBOR as field names in structures
> fix: Handle byte strings for field names

- ciborium-io/src/lib.rs
Checking the project with the latest `clippy` tool raises the following error in the `ciborium-ll` crate:
```rust
$ cargo +stable clippy -- -V
clippy 0.1.66 (69f9c33 2022-12-12)
$ cargo +stable clippy --no-default-features
Checking ciborium-io v0.2.0 (/home/vpetrigo/projects/rust/ciborium/ciborium-io)
error: replacing a value of type `T` with `T::default()` is better expressed using `std::mem::take`
--> ciborium-io/src/lib.rs:139:32
|
139 |         let (prefix, suffix) = core::mem::replace(self, &mut []).split_at_mut(data.len());
|                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using: `std::mem::take(self)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_with_default
note: the lint level is …
```
> Update no-std write_all implementation to use mem::take

- ciborium-io/Cargo.toml
- ciborium-ll/Cargo.toml
- ciborium/Cargo.toml
Prep for a v0.2.1 release.
Ref https://github.com/enarx/ciborium/pull/77
> chore: release 0.2.1

- ciborium/src/value/de.rs
- ciborium/src/value/ser.rs
CBOR is not a human-readable format and so `is_human_readable` should be overridden in the Serializer and Deserializer traits, which return true by default. 
https://docs.rs/serde/latest/serde/trait.Deserializer.html#method.is_human_readable
> fix: is_human_readable should be false

- ciborium/src/de/mod.rs
- ciborium/tests/recursion.rs
This change adds a from_reader_with_recursion_limit() variant of from_reader(), allowing the maximum recursion limit to be set explicitly.
Fixes #58 which asks for the ability to set a higher recursion limit, but this is mainly intended for environments where the default limit of 256 is too large (i.e. the stack gets exhausted before the limit is hit).
> feat: add from_reader_with_recursion_limit

- ciborium-ll/src/dec.rs
- ciborium/src/de/error.rs
Spellcheck in error type in ciborium docs.
Link: https://docs.rs/ciborium/latest/ciborium/de/enum.Error.html#variant.Io
>Contains the underlying error "reaturned" while reading.
> Update spelling for error type in ciborium docs

- ciborium/Cargo.toml
This allows ciborium to build with the `-Z minimal-versions` cargo flag.
---
Currently, ciborium specifies serde v1.0 as its dependency. This may be problematic since version v1.0.0 of serde doesn't allow ciborium to build, so if a project was using version an early version of serde and pulled in ciborium, their project would fail to build until they update serde to a later version. Additionally, any project that pulls in ciborium would fail to build using the `-Z minimal-versions flag`. Since ciborium is used by popular crates such as criterion, this affects a large part of the ecosystem.
Testing was done using `cargo +nightly -Z minimal-versions update && cargo test --all-features`, and through manual bisecting I found v1.0.100 to be the earliest version of serde that works and passes …
> Correctly set minimum serde version to v1.0.100

- ciborium-ll/Cargo.toml
The reason for the update of the `half` library is the `no_std` support.
The old version did not have `std` feature and was trying to use `fmodf` function from the standard math library, which is not available on `no_std` environment (at least on windows).
> Update `half` library

- ciborium/src/value/de.rs
- ciborium/src/value/ser.rs
Clippy from Rust 1.75 onward has a check for use of fallible conversion when an infallible conversion would have done the trick.
> fix: satisfy clippy

- ciborium-io/Cargo.toml
- ciborium-io/src/eio.rs
- ciborium-io/src/lib.rs
Hello, please consider merging this optional feature.
> feat: add adapters around embedded-io::{Read, Write} implementing Read, Write

- ciborium/src/de/mod.rs
Hello,
please accept this pull request, it allow user to use seeded deserializers, like this:
```
let des = AuthListDeserializer {
auth_entry_visitor: Some(|e: AuthListEntry| println!("{e:?}")),
};
let file_in = std::fs::OpenOptions::new().read(true).open(pth)?;
let mut scratch = [0u8; 16];
let auth_list = des.deserialize(&mut ciborium::de::deserializer_from_reader_with_buffer(file_in, &mut scratch))?;
```
> Add methods returning just the deserializer

- ciborium/tests/fuzz.rs
> fix: only run the fuzz tests on unix

- ciborium/tests/codec.rs
> fix: release mode NaN test failure

- ciborium/tests/error.rs
> Add more tests from RFC8949.

- ciborium-ll/src/seg.rs
- ciborium/tests/error.rs
- ciborium/tests/recursion.rs
> fix: indefinite strings can't contain indefinite strings

- ciborium-ll/src/dec.rs
- ciborium-ll/src/enc.rs
- ciborium-ll/src/seg.rs
- ciborium/src/de/mod.rs
- ciborium/src/ser/mod.rs
This will allow future changes to enable zero copy deserialization to avoid more complicated bounds on various types.
> refactor: remove unnecessary bounds from types

- ciborium/src/value/de.rs
Invalid data can lead to allocating too much memory. Only preallocate up to 1024 `Value` objects.
Fixes: #115
> fix: invalid allocation requests

- ciborium/src/value/de.rs
allow to deserialize bytes from a `Value::Array(Integer)`
[matches the behaviour of serve_json](https://docs.rs/serde_json/latest/src/serde_json/value/de.rs.html#360-370)
should we also allow to deserialize bytes from `Value::Text` ?
> feat: deserialize bytes from Value Array

- ciborium/src/de/mod.rs
- ciborium/src/value/de.rs
The `TagAccess` type from the `ciborium::de` module seems to be unused.
Only the `crate::tag::TagAccess` is used.
So I removed it and replaced the qualified path `crate::tag::TagAccess` with a `use` import.
Additionally a header pull followed by a push was also removed, since it
1. didn't forward the decoder in any important way and
2. the pulled header wasn't actually used.
> refactor: remove unused code from deserializer

- ciborium/src/lib.rs
- ciborium/src/ser/mod.rs
- ciborium/tests/codec.rs
Such shortcut is usually included in serde format libraries
refinement of #128
> feat: implement ser::to_vec() for convenient serializing into a new Vec<u8>

- ciborium-ll/src/enc.rs
- ciborium-ll/src/hdr.rs
This PR adds a roughly 20% speed improvement to serialization in my application benchmarks. 
The use of `#[inline(always)]` is required because LLVM sees the function as "large" and avoids inlining a plain `#[inline]` hint. However, almost all usage of these methods in ciborium specify the enum at compile-time, which means this "large" function can be optimised to a small set of instructions and remove many branches.
I could add a `ciborium-bench` crate into the workspace using criterion to demonstrate this if this change is likely to be accepted? Cheers!
---
One minor concern is compiling with opt_level `s` or `z`, where application developers may prefer a smaller bundle size (such as WASM use cases). We could use a `smaller-bundle` feature flag for this case, and use …
> Aggressive inlining (+20% serialization speed boost)

- ciborium/src/ser/error.rs
> Fix typo in ciborium::ser::Error doc comment

- ciborium/src/value/canonical.rs
- ciborium/src/value/mod.rs
- ciborium/tests/canonical.rs
Closes #144, add `canonical_into_vec`, `canonical_into_writer` and `canonical_value`
> Closes #144, add `canonical_into_vec`, `canonical_into_writer`, `canonical_value`

- ciborium/src/ser/mod.rs
Calculate the leading zero bytes with straight line integer operations instead of a looping search. This generates fewer instructions with no branching.
> refactor: improve 128-bit integer serialization
